[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Environment variables to set in Railway dashboard:
# SUPABASE_URL = "your-supabase-url"
# SUPABASE_SERVICE_KEY = "your-supabase-service-key"  
# SUPABASE_JWT_SECRET = "your-jwt-secret"
# ALLOWED_ORIGINS = "https://your-frontend-domain.com,http://localhost:3000"
# PORT is automatically set by Railway