[build]
builder = "nixpacks"
buildCommand = "python -m pip install --upgrade pip && pip install -r requirements.txt"

[deploy]
startCommand = "python start.py"
restartPolicyType = "always"

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"